apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-deployment
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
        - command: ["cloudflared"]
          args: ["tunnel", "--metrics", "0.0.0.0:2000", "--no-autoupdate", "run", "--token-file", "/etc/cloudflared/token"]
          image: cloudflare/cloudflared:2025.4.2
          name: cloudflared
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: cloudflared-secret
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-secret
          secret:
            secretName: cloudflared-secret
