---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA5CTAbuG/e3mPdL9pWUeCh/OcnI1Elo2u4xahysHQIpXG7TmsOpLJzgW3fEubFq0Jg8ZKhtHdiRmGF9bCCs1jFXIax7TNbkapd5ar9FVxqx4sOKq/iqIneOqeqTSjUzVEa5h42YYEhJRVgTnZpkjZzCO5f3JTs/Pyvbjai2RCfQpr+JvqPLn1v4gf2dMzCZ9s4QXfgfVfWMDeIopZ60iSJvoCMOKhjiinmzeYgjxVipQ7pgQKVdW8EFoEmnFatCrvUneIJEHt190qkdAzE5hkeS5WwCs8ircfzFCyUxfgo0lpWnzOtgg/w6rrtRLVcKcDZp/JXpDGF5doMPqbvsRUTM3ibv1vQgdxLDExyAq3RK1+X9ZqNMOulWGFFtOUKuCEDWJPnJ9e8UEh4499VzPQ5oY3w2Ulsj2y0xhy0T/D4DpNLhiWGGMR8Mp1x3RIGSZdPPtiO8Me2EmXSWil/1RtVW7YI9fsIUNZJo/H/qZ6PrNo+c7G1CK2UoCkyd20aNO/daXcRsXV8BqscvQhGZ++lIyn8d8ibt536oI6gq5MyB2+yPYyO9Y05sCqeDDHEBt/AqkM/jX0EQjolQmRnKcWOhelUwxwmfXEKJhWFER9ZUfCfyHBeuTH1yhWvDlY8W9mBFRSKNz0njqWzluUTFKE5c+a841OXhdZW6uiE97IUkZOeFlbclRFxUa7Q6sIqnv/P1jBLPBWN/RsfJft8VaI1kEBbFHfLhyTBoBlD/wp0HvgGPOAuFfBVdSgt3qQjHJyBvMcknzMmCAiT8pWGGmGNEQPPmH65zL7QD6hC+wzGEQhHtfO/5WFzC0DwPz+DkP0i6O0PXTIPJC3cSKXpK6H//27xjQEaK3U7p9+Yh5nTuV1Qja7PgppRzURu4AL+dy6C2H6n8oT0Vq0RqO0qeiV/KmW85PFKOFLCnulEd7n1vLAI0F+buL7r
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
