---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBjUhFMDZ0EX7K8PUEEH2XHc1SOf6eW466LqP0JULjuj6o3oh2HoNqEUsawG3tH9o5ymUk2wEzbqkzsUanSWw5yX0rQheqPxhfNcIR+f5KVGJiPxem3ZMSkqgDHQuF9EzEQGnzyut/lPZ+HUskxhQ0QD/S9/CM5vr7APdFtaE9FkssKUGcoB87HhQxVqmpI0gTILzPCvwrIL7gWvo/MTbDDTbiHlMX30jBzMw00EypE3412UY3eq1Ht1AddJOLxLlvqv/ryk7F3ummCEAkY3XH5gwR9CaHNs3Lkp5XRroaZJQVGNhsB61RSs/uAktipt7uqzcpipeyCYvMUM9rtti2Wuj9EWfmNoY8Ab+pZ2HTuBxTXfVTwiDebsT9tFZ50Dyh98zHRt80vxEDsE1uOxWEJRYnKgLXezOguqDv2jQ/A+qczg41ZP82Vi5E8+XEhHiM6zgBYrOaIKBu3vqHI47qXtomLf4xTJVUnMl8o+3xmWIGpfKPfvS4xwzqDCKED/4+c2HU0e0aHglsrpUaEXjxZZIRd1b8yuX//EjbDR4BdMDf+0AjD3ycETyuwWsTpRz5ZWIKnSEScsVzg1BbfpBnM6BXwwqbPEjtlQHV95shj/ipKOoj8JuO50Ln+YYJ5+qeWVVWS0DAPwFQN7DlLnUHHuJ7WjSD82vuoijUAGhIwt6TeGkwt6OV820qTZk5ZCX8umsZk9tAwjFfzfn3jCh04qzERZfNKxeaJ1DB1H4Ymq3TyVTEfMdTBOaMOJVWMbcNX7ALydzQDOz+Q28YpkSuzrosNYy9aXt+/cjm7aiBHrchFgoN0LgUjYCACVfuIwn5HmcnW8xBqWbQQprRC8Fx6KftFXMCLU2WHe7c1It2EUcI8o8beD3cncgkzaysAjHIMW8AHPbKF3RlzJIBENXBgzT0eFFRKj+8g86PETzgzRY4Nb/LIEWPb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
