apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - image: vaultwarden/server:1.33.2-alpine
        name: vaultwarden
        env:
          - name: DOMAIN
            value: "https://vw.camillevauchel.fr"
          - name: SIGNUPS_ALLOWED
            value: "false"
          - name: INVITATIONS_ALLOWED
            value: "false"
          - name: SHOW_PASSWORD_HINT
            value: "false"
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: vaultwarden-data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
