---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rebot-secret
  namespace: rebot
spec:
  encryptedData:
    DISCORD_TOKEN: AgCpJRt2phaF5ZVoXM3yEOB2+sO96IJ2Bp/zGng9ZXBc4qpIdiyx3qQQ1aYky1mYNpjc1FF0d5C4AiYx5tUtM4xpbQF/UqPETFEiR1U319hsbhLu99v30AGuUZ/JpYiNSt69hnc3GHG7M2E0njrb+20N2ViXdBb+v23Rx7R+NHzOkudWD5Wrzzpox/qEXuwfZ2dQxXFAd4+AiLOFAMo5epoSHsoepW4t/PHmzl1QvJkfCzqDJQQ38znUuUUfFuXCx7YekmnuEduxDldTXMTGqZ5d9Uc61RGOZ2jf5cTP0HLIZP5iP0V6PgBkIKwhMoS1BXlpCrxh6FOG7bWTSXJNFByRxGkngOuu1n2yjrfw3lJq6KdJ6lrdQRaiFveVrs/x8PAaPGmnwAeBknssD1vMSGD56lQuvQJf23fQoU7tolbP6mNGENcCG4EfNcL2PtdE90o+agI7Q2lqZ81U/EmkuxUilCRNgVnoQCfcXdsonxjZ1SV5IO1WiX2MblCfWqgARmDVFRgsuaCCnFgNzrlDe8BpQrRQ3IZ07IDzt3oDCtwKpjDYNLcE4YZe8+Wi8z1E4b7d/wEzwrtONG3Ul0Vfia4vzLMKkeM/K20NPnQLOL2qt4VQb90wDAwuBWGoews2JGrnz+FFuRNrZHw/Urh00vUJjsX5/GiLYiMC4RLH0DWo1hznO7yTw2riXfYw8XHfdF2ijrY6vGx0H1sJxoOL9Dk6mAc1X89J1+lhGnXo5FaO9p4LFKI9EVjUAenuj+zMHR2XQpo8m0bUBoxx+n71N1B8ld/fX9L6mLY=
  template:
    metadata:
      creationTimestamp: null
      name: rebot-secret
      namespace: rebot
