apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rebot
  name: rebot
spec:
  selector:
    matchLabels:
      app: rebot
  replicas: 1
  template:
    metadata:
      labels:
        app: rebot
    spec:
      containers:
      - name: rebot
        image: camzor/rebot
        envFrom:
          - configMapRef:
              name: rebot-config
          - secretRef:
              name: rebot-secret

