apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rebot-pvc
  namespace: rebot
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
