apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rebot
  name: rebot
spec:
  selector:
    matchLabels:
      app: rebot
  replicas: 1
  template:
    metadata:
      labels:
        app: rebot
    spec:
      containers:
      - name: rebot
        image: camzor/rebot:1.1.0
        envFrom:
          - configMapRef:
              name: rebot-config
          - secretRef:
              name: rebot-secret
        volumeMounts:
          - mountPath: /data
            name: rebot-data
        imagePullPolicy: IfNotPresent
      volumes:
        - name: rebot-data
          persistentVolumeClaim:
            claimName: rebot-pvc

